version: '3.1'

services:
    mariadb:
        image: bitnami/mariadb:10.3
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=MTIzNDU2Nzgq
            - MARIADB_USER=drupal
            - MARIADB_DATABASE=ecommerce
            - MARIADB_PASSWORD=MTIzNDU2Nzgq
            - ALLOW_EMPTY_PASSWORD=no
        volumes:
            - 'mariadb_data:/bitnami'
        ports:
            - '3307:3306'

    drupal:
        image: bitnami/drupal:latest
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - MARIADB_ROOT_PASSWORD=MTIzNDU2Nzgq
            - DRUPAL_DATABASE_NAME=ecommerce
            - DRUPAL_DATABASE_USER=drupal
            - DRUPAL_DATABASE_PASSWORD=MTIzNDU2Nzgq
            - ALLOW_EMPTY_PASSWORD=no
            - DRUPAL_PROFILE=standard
            - DRUPAL_USERNAME=elarduino
            - DRUPAL_PASSWORD=Elarduino46*_*
        ports:
            - '8082:80'
            - '443:443'
        volumes:
            - 'drupal_data:/bitnami'
        depends_on:
            - mariadb

volumes:
    mariadb_data:
        driver: local
    drupal_data:
        driver: local