version: '3.1'

services:

  db-wordpress:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MTIzNDU2Nzgq
      MYSQL_ROOT_PASSWORD: MTIzNDU2Nzgq
    container_name: db-wordpress
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: MTIzNDU2Nzgq
      WORDPRESS_DB_NAME: ecommerce
      WORDPRESS_TABLE_PREFIX: "wp_"
    depends_on:
      - db-wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
      - .config/php.ini:/var/www/html/php.ini

  wordpress-cli:
    depends_on:
      - db-wordpress
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 20;
      wp core install
      --path="/var/www/html"
      --url="http://134.209.217.128"
      --title="Amani Aventure"
      --admin_user=Amani123 --admin_password=2Cpcw$8e1tP&62hYR!
      --admin_email=valent.2696@gmail.com &&
      wp language core install es_ES --activate &&
      wp plugin install all-in-one-wp-migration --activate
      '
    container_name: wordpress-cli
    volumes:
      - wordpress:/var/www/html

volumes:
  db:
  wordpress:
