version: "3.1"

services:
  drupal:
    stdin_open: true
    tty: true
    image: drupal:8-apache
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
    restart: always
    links: 
      - mysql

  mysql:
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: MTIzNDU2Nzgq
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: drupal
      MYSQL_PASSWORD: MTIzNDU2Nzgq

volumes:
  db-data:
