version: '3.1'

services:

  db-wordpress:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MTIzNDU2Nzgq
      MYSQL_ROOT_PASSWORD: MTIzNDU2Nzgq
    container_name: db-wordpress
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:5.3.2-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: MTIzNDU2Nzgq
      WORDPRESS_DB_NAME: ecommerce
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    depends_on:
      - db-wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
      - .config/.media-size-configuration:/var/www/html/.media-size-configuration

  wordpress-cli:
    depends_on:
      - db-wordpress
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:8080" --title="Tienda de Hardware El arduino" --admin_user=elarduino --admin_password=Elarduino46*_* --admin_email=elarduino46@gmail.com
      && wp plugin install all-in-one-wp-migration --activate
      '
    container_name: wordpress-cli
    volumes:
      - wordpress:/var/www/html

volumes:
  db:
  wordpress: