version: '3.1'

services:

  db-wordpress:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MTIzNDU2Nzgq
      MYSQL_ROOT_PASSWORD: MTIzNDU2Nzgq
    container_name: db-wordpress
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build: .
    ports:
      - 8080:80 
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: MTIzNDU2Nzgq
      WORDPRESS_DB_NAME: ecommerce     
    depends_on:
      - db-wordpress
    container_name: wordpress
    volumes: 
      - wordpress:/var/www/html  

volumes:
  wordpress:
  db:



