version: '3.1'

services:

  wordpress:
    image: wordpress:5.3.2-php7.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: MTIzNDU2Nzgq
      WORDPRESS_DB_NAME: ecommerce
    volumes:
      - wordpress:/var/www/html

  db-wordpress:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: MTIzNDU2Nzgq
      MYSQL_ROOT_PASSWORD: MTIzNDU2Nzgq
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:



